Controllers/AdsController.cs
using cloudscribe.Pagination.Models;
using CountryhouseService.Models;
using CountryhouseService.Repositories;
using CountryhouseService.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CountryhouseService.Controllers
{
    public class AdsController : Controller
    {
        private readonly IAdRepository _adRepository;
        private readonly IStatusRepository _statusRepository;
        private readonly IUserRepository _userRepository;
        private readonly IImageRepository _imageRepository;
        private readonly IWebHostEnvironment _env;

        public AdsController(IAdRepository adRepository, 
            IStatusRepository statusRepository, 
            IUserRepository userRepository, 
            IImageRepository imageRepository, 
            IWebHostEnvironment env)
        {
            _adRepository = adRepository;
            _statusRepository = statusRepository;
            _userRepository = userRepository;
            _imageRepository = imageRepository;
            _env = env;
        }

        [HttpGet("Ads/{id:int}")]
        public async Task<IActionResult> Ad(int? id)
        {
            if (id != null && id > 0)
            {
                Ad ad = await _adRepository.FindByIdAsync(id, a => a.Author);


                if (ad != null)
                {
                    await _adRepository.LoadImagesAsync(ad);
                    User user = null;
                    if (_userRepository.IsSignedIn(User)) user = await _userRepository.GetSignedInUserAsync(User);
                    AdPagedResult result = new AdPagedResult
                    {
                        Ad = ad,
                        UserRole = user != null ? (await _userRepository.GetRolesAsync(user) as List<string>).First() : null,
                        IsCurrentUser = (user?.Id == ad.AuthorId).ToString(),
                    };
                    return View(result);
                }
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Index(string sortBy, string searchString, string showCurrentUserData, int page = 1, int pageSize = 5)
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            PagedResult<Ad> pagedResult = await _adRepository.CreateSearchResultAsync(sortBy, searchString, showCurrentUserData, userId, page, pageSize);
            await _adRepository.LoadImagesAsync(pagedResult.Data);

            AdsListPagedResult result = new AdsListPagedResult
            {
                Ads = pagedResult,
                CurrentSortOrder = sortBy,
                CurrentSearchString = searchString,
                ShowCurrentUserData = showCurrentUserData,
            };
            return View(result);

        }

        [HttpGet]
        [Authorize(Roles = "Owner")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> Create(AdViewModel adViewModel)
        {
            if (ModelState.IsValid)
            {
                AdStatus status = await _statusRepository.FindByNameAsync("Published");
                string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                List<Image> images = new List<Image>();
                if (adViewModel.Images != null)
                {
                    images = await _imageRepository.SaveRangeAsync(adViewModel.Images);
                }


                int newAdId = await _adRepository.CreateAsync(adViewModel, images, currentUserId, status);

                TempData["isSuccess"] = "true";
                ViewData["AdId"] = newAdId;
                ModelState.Clear();
                return View();
            }
            return View(adViewModel);
        }


        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id != null && id > 0)
            {
                string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                Ad ad = await _adRepository.FindByIdAsync(id);
                if (ad != null && ad.AuthorId == currentUserId)
                {
                    await _adRepository.LoadImagesAsync(ad);
                    if (ad.Images != null)
                    {
                        _imageRepository.RemoveRange(ad.Images);
                    }

                    await _adRepository.RemoveAsync(ad);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id != null && id > 0)
            {
                string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                Ad ad = await _adRepository.FindByIdAsync(id, a => a.Author);

                if (ad != null && ad.AuthorId == currentUserId)
                {
                    await _adRepository.LoadImagesAsync(ad);
                    AdViewModel result = new EditAdViewModel
                    {
                        Id = ad.Id,
                        Title = ad.Title,
                        Description = ad.Description,
                        Address = ad.Address,
                        Budget = ad.Budget,
                        ContactNumber = ad.ContactNumber,
                        FromDate = ad.FromDate,
                        UntilDate = ad.UntilDate,
                    };
                    return View(result);
                }
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Owner")]
        public async Task<IActionResult> Edit(EditAdViewModel adViewModel)
        {
            if (ModelState.IsValid)
            {
                if (adViewModel.Id > 0)
                {
                    string currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    Ad ad = await _adRepository.FindByIdAsync(adViewModel.Id, a => a.Author);
                    if (ad != null && ad.AuthorId == currentUserId)
                    {
                        await _adRepository.LoadImagesAsync(ad);
                        if (ad.Images != null)
                        {
                            _imageRepository.RemoveRange(ad.Images);
                        }

                        List<Image> images = new List<Image>();
                        if (adViewModel.Images != null)
                        {
                            images = await _imageRepository.SaveRangeAsync(adViewModel.Images);
                        }

                        await _adRepository.UpdateAsync(ad, adViewModel, images);

                        TempData["isSuccess"] = "true";
                        return View(adViewModel);
                    }
                }
                return RedirectToAction("Index");
            }
            return View(adViewModel);
        }
    }
}

Controllers/UsersController.cs
using CountryhouseService.Data;
using CountryhouseService.Models;
using CountryhouseService.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CountryhouseService.Controllers
{
    public class UsersController : Controller
    {
        private readonly AppDbContext _db;
        private readonly UserManager<User> _userManager;

        public UsersController(AppDbContext db, UserManager<User> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public async Task<IActionResult> Profile(string userId, string showCurrentUserData)
        {
            if (!string.IsNullOrEmpty(showCurrentUserData))
                userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            User user = await _db.Users.AsNoTracking().FirstOrDefaultAsync(u => u.Id == userId);
            if (user == null) return RedirectToAction("Index", "Home");
            IEnumerable<string> roles = await _userManager.GetRolesAsync(user);
            string role = roles.FirstOrDefault();
            ProfilePagedResult result = new ProfilePagedResult
            {
                User = user,
                Role = role,
                Avatar = user.AvatarSource ?? Constants.DefaultAvatarSource,
                ShowCurrentUserData = showCurrentUserData,
            };
            return View(result);
        }
    }
}

Views/Shared/_IndexLayout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@{
	string defaultLogoSource = Constants.DefaultLogoSource;
}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - CountryhouseService</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src=@defaultLogoSource style="height:25px; width:25px" /> Countryhouse Service</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Ads" asp-action="Index">Ads</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Index">Requests</a>
						</li>
					</ul>
					@if (SignInManager.IsSignedIn(User))
					{
						<ul class="navbar-nav">
							<li>
								<a class="btn btn-outline-primary mr-1" asp-area="" asp-controller="Users" asp-action="Profile" asp-route-showCurrentUserData="true">My Profile</a>
							</li>
							<li>
								<a class="btn btn-primary" asp-area="" asp-controller="Account" asp-action="Logout">Log Out</a>
							</li>
						</ul>
					}
					else
					{
						<ul class="navbar-nav">
							<li class="nav-item">
								<a class="btn btn-primary mr-1" asp-area="" asp-controller="Account" asp-action="SignIn">Sign In</a>
							</li>
							<li class="nav-item">
								<a class="btn btn-outline-primary" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
							</li>
						</ul>
					}

				</div>
			</div>
		</nav>
	</header>
	
	<div role="main">
		@RenderBody()
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			<div class="row justify-content-end">
				<div class="col-4 text-center">
					&copy; @DateTime.Today.Year - Countryhouse Service - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="flex-grow-1">Privacy</a>
				</div>
				<div class="col-4 text-right">
					<a asp-controller="Home" asp-action="About">About</a> |
					<a asp-controller="Home" asp-action="Rules">Rules</a>
				</div>
			</div>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
@{ 
    string defaultLogoSource = Constants.DefaultLogoSource;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CountryhouseService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src=@defaultLogoSource style="height:25px; width:25px" /> Countryhouse Service</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ads" asp-action="Index">Ads</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Index">Requests</a>
                        </li>
                    </ul>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav">
                            <li>
                                <a class="btn btn-outline-primary mr-1" asp-area="" asp-controller="Users" asp-action="Profile" asp-route-showCurrentUserData="true">My Profile</a>
                            </li>
                            <li>
                                <a class="btn btn-primary" asp-area="" asp-controller="Account" asp-action="Logout">Log Out</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="btn btn-primary mr-1" asp-area="" asp-controller="Account" asp-action="SignIn">Sign In</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-primary" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        </ul>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-4 text-center">
                    &copy; @DateTime.Today.Year - Countryhouse Service - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="flex-grow-1">Privacy</a>
                </div>
                <div class="col-4 text-right">
                    <a asp-controller="Home" asp-action="About">About</a> |
                    <a asp-controller="Home" asp-action="Rules">Rules</a>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_PaginationPartial.cshtml
<cs-pager cs-paging-pagenumber="@Model.Ads.PageNumber"
          cs-paging-totalitems="@Model.Ads.TotalItems"
          cs-paging-pagesize="@Model.Ads.PageSize"
          cs-pagenumber-param="page"
          asp-controller=@ViewData["Controller"]
          asp-action=@ViewData["Action"]
          asp-route-sortBy="@Model.CurrentSortOrder"
          asp-route-searchString="@Model.CurrentSearchString"
          asp-route-showCurrentUserData="@Model.ShowCurrentUserData"
          cs-pager-li-current-class="page-item active"
          cs-pager-li-other-class="page-item"
          cs-pager-li-non-active-class="page-item disabled"
          cs-pager-link-current-class="page-link"
          cs-pager-link-other-class="page-link"
></cs-pager>